# Generated by Django 5.1.3 on 2024-12-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_srudents_students"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Students",
        ),
    ]
