# Generated by Django 5.1.3 on 2024-11-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="tetle",
            new_name="title",
        ),
    ]
