# Generated by Django 5.1.3 on 2024-11-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_rename_tetle_category_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photopost",
            old_name="imagel",
            new_name="image1",
        ),
    ]
