# Generated by Django 5.1.3 on 2024-12-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="englishscore",
            name="user",
        ),
        migrations.AddField(
            model_name="englishscore",
            name="name",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="photo.students",
                verbose_name="生徒",
            ),
            preserve_default=False,
        ),
    ]
