# Generated by Django 5.1.3 on 2024-11-25 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0004_englishwords_englishsscore"),
    ]

    operations = [
        migrations.AddField(
            model_name="englishwords",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="photo.category",
                verbose_name="カテゴリ",
            ),
            preserve_default=False,
        ),
    ]
